ARG FEDORA_MAJOR_VERSION=40
FROM ghcr.io/xtruder/fedora-workstation:${FEDORA_MAJOR_VERSION}

RUN /tmp/scripts/install_tuxedo.sh && \
    /tmp/scripts/install_rocm.sh

RUN /tmp/scripts/ostree_commit.sh
